services:
- type: web
  name: al-web
  env: node
  rootDir: apps/web
  plan: free
  buildCommand: yarn; yarn build
  startCommand: yarn start
  autoDeploy: true
  envVars:
  - key: NODE_ENV
    value: production
